@echo off

powershell.exe -ExecutionPolicy ByPass -Command "& C:\Nubeva-RN-Sensor.msi AWS=eyJhY2Nlc3MiOiJBS0lBWVFGV1ZJQ1FLNUdBUFlISiIsInNlY3JldCI6Ik9EdmJEM2dnNUtPcmFQeEJNcWZreXdyQnZmd1owdmxBc0VMR0VzSkMiLCJyZWdpb24iOiJ1cy1lYXN0LTEiLCJkZGIiOiJOdWJldmFSUi1OdWJldmFSUkRCVGFibGUtMVcwWlIzVzZQNlJKSiIsImNsb3Vkd2F0Y2giOiJOdWJldmFSUi1OdWJldmFSUiJ9 /qn"

exit

